version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:10.12
    working_directory: ~/anidb
    steps:
      - checkout

      - run:
          name: Installing dependenices
          command: yarn install --frozen-lockfile

      - persist_to_workspace:
          root: node_modules
  test:
    docker:
      - image: circleci/node:10.12-browsers
    working_directory: ~/anidb
    environment:
      CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout

      - attach_workspace:
          at: ~/anidb/node_modules

      - run:
          name: Testing source code
          command: yarn test

      - run:
          name: Uploading coverage to Codecov
          command: yarn codecov --token=$CODECOV_TOKEN
  deploy:
    docker:
      - image: circleci/node:10.12
    working_directory: ~/anidb
    steps:
      - checkout

      - attach_workspace:
          at: ~/anidb/node_modules

      - run:
          name: Building source code
          command: yarn build

      - run:
          name: Deploying to Firebase
          command: ./node_modules/.bin/firebase deploy --project "rin-anidb" --only hosting --token=$FIREBASE_DEPLOY_TOKEN --non-interactive
workflows:
  version: 2
  build:
    jobs:
      - setup
      - test:
          requires:
            - setup
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - setup
          filters:
            branches:
              only: master
