version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12
    branches:
      only:
        - master
        - ngx
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependenices
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules

      # - run:
      #     name: Code testing
      #     command: yarn test

      - run:
          name: Building source code
          command: yarn build

      - run:
          name: Deploying to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --non-interactive

