version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    branches:
      only:
        - master
    steps:
      - checkout

      - run:
          name: Installing dependenices
          command: yarn install --frozen-lockfile

      - run:
          name: Testing source code
          command: yarn test

      - run:
          name: Uploading coverage to Codecov
          command: yarn codecov --token=$CODECOV_TOKEN

      - run:
          name: Building source code
          command: yarn build

      - run:
          name: Deploying to Firebase
          command: ./node_modules/.bin/firebase deploy --project "rin-anidb" --only hosting --token=$FIREBASE_DEPLOY_TOKEN --non-interactive

      - run:
          name: Deploying to Zeit
          command: ./node_modules/.bin/now -t $NOW_DEPLOY_TOKEN dist -A ../now.json && ./node_modules/.bin/now -t $NOW_DEPLOY_TOKEN alias anidb
          no_output_timeout: 35s

      - run:
          name: Removing previous Zeit deployments
          command: ./node_modules/.bin/now -t $NOW_DEPLOY_TOKEN rm "Rin's Anime Database" --safe --yes
          no_output_timeout: 8s
