# build:
#   docker:
#     - image: circleci/node:10.12
#   steps:
#     - checkout

#     - restore_cache:
#       key: dependency-cache-{{ checksum "yarn.lock" }}
#     - run: yarn install
#     - save_cache:
#       key: dependency-cache-{{ checksum "yarn.lock" }}
#       paths:
#         - ~/.cache/yarn
#         - ./node_modules

#     - run: yarn build-np

# deploy:
#   working_directory: /dist
#   steps:
#     - run:
#       name: Deploy to Firebase
#       command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --non-interactive

# workflows:
#   version: 2
#   -deploy:
#     jobs:
#       build
#       deploy:
#         requires:
#           - build
#         filter:
#           branches:
#             only: ngx

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Installing dependenices
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules

      # - run: yarn test
      - run:
          name: Building source code
          command: yarn build-np

      - run:
          name: Deploying to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN --non-interactive

