version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    branches:
      only:
        - master
    steps:
      - checkout

      - run:
          name: Installing dependenices
          command: yarn install --frozen-lockfile

      - run:
          name: Testing source code
          command: yarn remove netlify-cli && yarn test && yarn add --dev netlify-cli

      - run:
          name: Uploading coverage to Codecov
          command: yarn codecov --token=$CODECOV_TOKEN
          no_output_timeout: 15s

      - run:
          name: Building source code
          command: yarn deploy

      # - run:
      #     name: Deploying to Firebase
      #     command: ./node_modules/.bin/firebase deploy --project "rin-anidb" --only hosting --token=$FIREBASE_DEPLOY_TOKEN --non-interactive

      - run:
          name: Deploying to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --message $SHORT_GIT_HASH --prod --dir=dist
          environment:
            SHORT_GIT_HASH: $(git log --format=oneline -n 1 $CIRCLE_SHA1)
