version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1-browsers
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"

    branches:
      only:
        - master
    steps:
      - checkout

      - run:
          name: Setting up environmental variables
          command: echo 'export COMMIT_MESSAGE=$(git log --format=%B -n 1 $CIRCLE_SHA1)' >> $BASH_ENV

      - run:
          name: Installing dependenices
          command: yarn install --frozen-lockfile

      - run:
          name: Testing source code
          command: yarn remove netlify-cli && yarn test && yarn add --dev netlify-cli

      - run:
          name: Uploading coverage to Codecov
          command: ./node_modules/.bin/codecov --token=$CODECOV_TOKEN
          no_output_timeout: 15s

      - run:
          name: Building source code
          command: yarn deploy

      - run:
          name: Deploying to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --message "$COMMIT_MESSAGE" --prod --dir=dist
