version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.4.0

    branches:
      only:
        - master

    steps:
      - checkout

      - run:
          name: Setting up environmental variables
          command: echo 'export COMMIT_MESSAGE=$(git log --format=%B -n 1 $CIRCLE_SHA1)' >> $BASH_ENV

      - run:
          name: Installing dependenices
          command: yarn install --frozen-lockfile

      - run:
          name: Building source code
          command: yarn deploy

      - run:
          name: Deploying to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --message "$COMMIT_MESSAGE" --prod --dir=dist
